#!/usr/bin/env bash
WORKSPACE=/workspaces/ha-salutespeech
git config --global --add safe.directory $WORKSPACE

ln -s ${WORKSPACE}/custom_components /config
ln -s ${WORKSPACE}/configuration.yaml /config/configuration.yaml
ln -s /usr/src/homeassistant/homeassistant custom_components/salute_stt/

pip3 install -r requirements.dev.txt
